Repository infiniteoverflow/Libro, pull requests merged in 2021-03, with the labels that each got.

#10 added lint dependency and file
  analysis_options.yaml
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#14 Added Login screen and SignUp screen using toggle button
  assets/images/arrowImage1.png
  assets/images/authBG 1.png
  lib/Screens/Login_Screen.dart
  lib/Utils/Styles.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#18 Created Contributing.md file
  Contributing.md
  pubspec.lock
Labels: GSSOC21, Level0

#19 configured firebase settings for ios
  .gitignore
  ios/Runner/Info.plist
  pubspec.lock
Labels: GSSOC21, Level2

#28 Email and Password Authentication Added With Email Verification
  android/app/build.gradle
  android/app/src/main/kotlin/com/example/libro/MainActivity.kt
  android/libro_android.iml
  lib/Screens/Login_Screen.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#31 Added Google Auth (#5)
  .flutter-plugins-dependencies
  lib/Screens/Login_Screen.dart
  lib/Screens/home_screen.dart
  lib/Services/google_sign_in.dart
  lib/generated_plugin_registrant.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#41 Homescreen UI Addition
  .flutter-plugins-dependencies
  android/gradle/wrapper/gradle-wrapper.properties
  assets/images/book1.jpg
  assets/images/book2.jpeg
  assets/images/book3.jpeg
  assets/images/books-bg.jpg
  lib/Screens/Login_Screen.dart
  lib/Screens/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#43 Created Pull Request Template
  .github/pull_request_template.md
Labels: GSSOC21, Level0

#44 Added Contributor
  README.md
Labels: GSSOC21, Level0

#45 Github Actions for labels and flutter build
  .flutter-plugins-dependencies
  .github/workflows/ci.yaml
  .github/workflows/label.yml
  .github/workflows/pull_request_ci.yml
  .gitignore
  analysis_options.yaml
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level1

#51 Created Info screen to gather info of user
  lib/Screens/info_screen.dart
Labels: GSSOC21, Level2

#53 onGenerateRoute
  lib/Screens/Login_Screen.dart
  lib/Screens/email_verification_screen.dart
  lib/Screens/home_screen.dart
  lib/Screens/info_screen.dart
  lib/Screens/intro_screen.dart
  lib/Services/facebook_sign_in.dart
  lib/Services/google_sign_in.dart
  lib/Utils/Styles.dart
  lib/Utils/constants..dart
  lib/main.dart
  lib/router/route_constants.dart
  lib/router/router.dart
Labels: GSSOC21, Level3

#56 Fixed render flex on email verification page
  lib/Screens/email_verification_screen.dart
Labels: GSSOC21, Level2

#60 Enabled crashlytics (android)
  .github/workflows/label.yml
  android/app/build.gradle
  android/build.gradle
  lib/Screens/Login_Screen.dart
  lib/Services/facebook_sign_in.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#61 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: GSSOC21, Level0

#63 Created bottom nav bar
  lib/Screens/chat_screen.dart
  lib/Screens/home_screen.dart
  lib/Screens/notifs_screen.dart
  lib/Screens/profile_screen.dart
Labels: GSSOC21, Level2

#67 Changed the logo and name of app
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: GSSOC21, Level1

#79 Optimised all asset images upto 17%
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  assets/images/Reading 1.png
  assets/images/Reading.png
  assets/images/Sharing 1.png
  assets/images/Sharing.png.png
  assets/images/arrowImage1.png
  assets/images/authBG 1.png
  assets/images/authBG.svg
  assets/images/book3.jpeg
  assets/images/fb.png
  assets/images/reading.svg
  assets/images/sharing.svg
  assets/images/twitter.png
  assets/images/verified.png
  assets/images/verify.svg
  mock.png
Labels: GSSOC21, Level1

#84 Added New Icons
  ios/Podfile.lock
  lib/Screens/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#83 Weak Password handled during SignUp
  lib/Screens/Login_Screen.dart
Labels: GSSOC21, Level2

#82 Added double back to exit on home screen
  lib/Screens/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#86 Added Login_screen SnackBar
  lib/Screens/Login_Screen.dart
Labels: GSSOC21, Level2
