Repository infiniteoverflow/Libro, pull requests merged in 2021-04, with the labels that each got.

#92 Added auto label for issues
  .github/workflows/issue.yml
Labels: GSSOC21, Level0

#99 Modified Verification Screen
  lib/Screens/Login_Screen.dart
  lib/Screens/email_verification_screen.dart
Labels: GSSOC21, Level2

#104 Issue#94 resolved
  README.md
Labels: GSSOC21, Level0

#111 made chat screen
  assets/images/emoji.png
  lib/Screens/chat_screen.dart
  lib/Screens/conversations.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level3

#112 Modified the Verified dialogue
  android/gradlew
  assets/images/verified.webp
  lib/Screens/email_verification_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: GSSOC21, Level2

#113 Resolved Issue "Adding a side drawer #101"
  lib/Screens/about_libro_screen.dart
  lib/Screens/home_screen.dart
  lib/router/route_constants.dart
  lib/router/router.dart
Labels: GSSOC21, Level2
